taco:
  orders:
    pageSize: 10

#log level setting    
logging:
  level:
    tacos: DEBUG

#spring properties
spring:
  jms:
    template:
      default-destination: tacocloud.order.queue
  rabbitmq:
    template:
      exchange: tacocloude.orders
      routing-key: kitchens.centrl
      receive-timeout: 30000
  kafka:
    template:
      default-topic: tacocloud.orders.topic
      bootstrap-servers:
      - kafaka.tacocloud.com:9092

    